const FIP_STATE_CODE = [
    {state: 'AL', code:01},
    {state: 'AK', code:02},
    {state: 'AZ', code:04},
    {state: 'AR', code:05},
    {state: 'CA', code:06},
    {state: 'CO', code:08},
    {state: 'CT', code:09},
    {state: 'DE', code:10},
    {state: 'DC', code:11},
    {state: 'FL', code:12},
    {state: 'GA', code:13},
    {state: 'HI', code:15},
    {state: 'ID', code:16},
    {state: 'IL', code:17},
    {state: 'IN', code:18},
    {state: 'IA', code:19},
    {state: 'KS', code:20},
    {state: 'KY', code:21},
    {state: 'LA', code:22},
    {state: 'ME', code:23},
    {state: 'MD', code:24},
    {state: 'MA', code:25},
    {state: 'MI', code:26},
    {state: 'MN', code:27},
    {state: 'MS', code:28},
    {state: 'MO', code:29},
    {state: 'MT', code:30},
    {state: 'NE', code:31},
    {state: 'NV', code:32},
    {state: 'NH', code:33},
    {state: 'NJ', code:34},
    {state: 'NM', code:35},
    {state: 'NY', code:36},
    {state: 'NC', code:37},
    {state: 'ND', code:38},
    {state: 'OH', code:39},
    {state: 'OK', code:40},
    {state: 'OR', code:41},
    {state: 'PA', code:42},
    {state: 'RI', code:44},
    {state: 'SC', code:45},
    {state: 'SD', code:46},
    {state: 'TN', code:47},
    {state: 'TX', code:48},
    {state: 'UT', code:49},
    {state: 'VT', code:50},
    {state: 'VA', code:51},
    {state: 'WA', code:53},
    {state: 'WV', code:54},
    {state: 'WI', code:55},
    {state: 'WY', code:56},
];

const NC_REGION_DICT = [
    {region: 'CABARRUS', conversion: 'Charlotte'},
    {region: 'GASTON', conversion: 'Charlotte'},
    {region: 'LINCOLN', conversion: 'Charlotte'},
    {region: 'MECKLENBURG', conversion: 'Charlotte'},
    {region: 'ROWAN', conversion: 'Charlotte'},
    {region: 'UNION', conversion: 'Charlotte'},
    {region: 'BEAUFORT', conversion: 'Coastal'},
    {region: 'BERTIE', conversion: 'Coastal'},
    {region: 'BLADEN', conversion: 'Coastal'},
    {region: 'BRUNSWICK', conversion: 'Coastal'},
    {region: 'CAMDEN', conversion: 'Coastal'},
    {region: 'CARTERET', conversion: 'Coastal'},
    {region: 'CHOWAN', conversion: 'Coastal'},
    {region: 'COLUMBUS', conversion: 'Coastal'},
    {region: 'CRAVEN', conversion: 'Coastal'},
    {region: 'CURRITUCK', conversion: 'Coastal'},
    {region: 'DARE', conversion: 'Coastal'},
    {region: 'DUPLIN', conversion: 'Coastal'},
    {region: 'GATES', conversion: 'Coastal'},
    {region: 'GREENE', conversion: 'Coastal'},
    {region: 'HERTFORD', conversion: 'Coastal'},
    {region: 'HYDE', conversion: 'Coastal'},
    {region: 'JONES', conversion: 'Coastal'},
    {region: 'LENOIR', conversion: 'Coastal'},
    {region: 'MARTIN', conversion: 'Coastal'},
    {region: 'NEW HANOVER', conversion: 'Coastal'},
    {region: 'NORTHAMPTON', conversion: 'Coastal'},
    {region: 'ONSLOW', conversion: 'Coastal'},
    {region: 'PAMLICO', conversion: 'Coastal'},
    {region: 'PASQUOTANK', conversion: 'Coastal'},
    {region: 'PENDER', conversion: 'Coastal'},
    {region: 'PERQUIMANS', conversion: 'Coastal'},
    {region: 'PITT', conversion: 'Coastal'},
    {region: 'TYRELL', conversion: 'Coastal'},
    {region: 'TYRRELL', conversion: 'Coastal'},
    {region: 'WASHINGTON', conversion: 'Coastal'},
    {region: 'ALEXANDER', conversion: 'Mountain'},
    {region: 'ANSON', conversion: 'Mountain'},
    {region: 'ASHE', conversion: 'Mountain'},
    {region: 'AVERY', conversion: 'Mountain'},
    {region: 'BUNCOMBE', conversion: 'Mountain'},
    {region: 'BURKE', conversion: 'Mountain'},
    {region: 'CALDWELL', conversion: 'Mountain'},
    {region: 'CATAWBA', conversion: 'Mountain'},
    {region: 'CHEROKEE', conversion: 'Mountain'},
    {region: 'CLAY', conversion: 'Mountain'},
    {region: 'CLEVELAND', conversion: 'Mountain'},
    {region: 'GRAHAM', conversion: 'Mountain'},
    {region: 'HAYWOOD', conversion: 'Mountain'},
    {region: 'HENDERSON', conversion: 'Mountain'},
    {region: 'IREDELL', conversion: 'Mountain'},
    {region: 'JACKSON', conversion: 'Mountain'},
    {region: 'MACON', conversion: 'Mountain'},
    {region: 'MADISON', conversion: 'Mountain'},
    {region: 'MCDOWELL', conversion: 'Mountain'},
    {region: 'MITCHELL', conversion: 'Mountain'},
    {region: 'POLK', conversion: 'Mountain'},
    {region: 'RICHMOND', conversion: 'Mountain'},
    {region: 'RUTHERFORD', conversion: 'Mountain'},
    {region: 'STANLY', conversion: 'Mountain'},
    {region: 'SWAIN', conversion: 'Mountain'},
    {region: 'TRANSYLVANIA', conversion: 'Mountain'},
    {region: 'WATAUGA', conversion: 'Mountain'},
    {region: 'YANCEY', conversion: 'Mountain'},
    {region: 'ALLEGHANY', conversion: 'Non-metro Piedmont'},
    {region: 'CASWELL', conversion: 'Non-metro Piedmont'},
    {region: 'CUMBERLAND', conversion: 'Non-metro Piedmont'},
    {region: 'DAVIE', conversion: 'Non-metro Piedmont'},
    {region: 'EDGECOMBE', conversion: 'Non-metro Piedmont'},
    {region: 'GRANVILLE', conversion: 'Non-metro Piedmont'},
    {region: 'HALIFAX', conversion: 'Non-metro Piedmont'},
    {region: 'HARNETT', conversion: 'Non-metro Piedmont'},
    {region: 'HOKE', conversion: 'Non-metro Piedmont'},
    {region: 'LEE', conversion: 'Non-metro Piedmont'},
    {region: 'MONTGOMERY', conversion: 'Non-metro Piedmont'},
    {region: 'MOORE', conversion: 'Non-metro Piedmont'},
    {region: 'NASH', conversion: 'Non-metro Piedmont'},
    {region: 'PERSON', conversion: 'Non-metro Piedmont'},
    {region: 'ROBESON', conversion: 'Non-metro Piedmont'},
    {region: 'ROCKINGHAM', conversion: 'Non-metro Piedmont'},
    {region: 'SAMPSON', conversion: 'Non-metro Piedmont'},
    {region: 'SCOTLAND', conversion: 'Non-metro Piedmont'},
    {region: 'STOKES', conversion: 'Non-metro Piedmont'},
    {region: 'SURRY', conversion: 'Non-metro Piedmont'},
    {region: 'VANCE', conversion: 'Non-metro Piedmont'},
    {region: 'WARREN', conversion: 'Non-metro Piedmont'},
    {region: 'WAYNE', conversion: 'Non-metro Piedmont'},
    {region: 'WILKES', conversion: 'Non-metro Piedmont'},
    {region: 'WILSON', conversion: 'Non-metro Piedmont'},
    {region: 'YADKIN', conversion: 'Non-metro Piedmont'},
    {region: 'ALAMANCE', conversion: 'Triad'},
    {region: 'DAVIDSON', conversion: 'Triad'},
    {region: 'FORSYTH', conversion: 'Triad'},
    {region: 'GUILFORD', conversion: 'Triad'},
    {region: 'RANDOLPH', conversion: 'Triad'},
    {region: 'CHATHAM', conversion: 'Triangle'},
    {region: 'DURHAM', conversion: 'Triangle'},
    {region: 'FRANKLIN', conversion: 'Triangle'},
    {region: 'JOHNSTON', conversion: 'Triangle'},
    {region: 'ORANGE', conversion: 'Triangle'},
    {region: 'WAKE', conversion: 'Triangle'},

];
